remote: true
hybrid: true
onsite: false

experience_level:
  internship: false
  entry: false
  associate: true
  mid_senior_level: true
  director: false
  executive: false

job_types:
  full_time: true
  contract: false
  part_time: true
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all_time: false
  month: false
  week: false
  24_hours: true

positions:
  - Flutter Developer
  - Cross Platform Developer

locations:
  - Germany
  - Canada
  - United States
  - United Kingdom
  - Saudi Arabia
  - UAE
  - London
  - Italy

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

location_blacklist:
  - Brazil

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: gemini
llm_model: gemini-1.5-flash-latest
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
